### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by BoltzmannBrain** [cortical-io/python-client-sdk#4]
The name "python-client-sdk" cannot be imported because of the "-" characters; python returns `SyntaxError: invalid syntax`. Please rename it to e.g. "python_client_sdk", "python.client.sdk", "pythonClientSDK", etc.

**Comment by tjagvad** [comment]
Maybe there is an issue - what operating system and python version are you using?

I cloned the repo in /tmp and using python2.7 I can
```python
import sys
sys.path.append("/tmp/python-client-sdk/python-client-sdk/")
```

without any errors.

On *nix based systems you should be able to add the client to the `PYTHONPATH` like this:
`export PYTHONPATH=$PYTHONPATH:/tmp/python-client-sdk/python-client-sdk/`

**Comment by rhyolight** [comment]
Even if it works, hyphens in a python module name [goes against PEP-8 guidelines](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).
