### ISSUE TITLE
Pip support?

### ISSUE THREAD

**Issue by DarkmatterVale** [cortical-io/python-client-sdk#9]
Are you guys planning on putting this SDK on pip? It would make installation much simpler, especially for people who do not want to have to spend a lot of time preparing their system.

**Comment by rhyolight** [comment]
:+1:

**Comment by ptkweller** [comment]
Great suggestion. I'll add this to our backlog.

**Comment by rhyolight** [comment]
@ptkweller I guess your backlog is not public? How will we know when this feature (and #8) has been added? Can you comment on these closed issues or keep them open until they are complete?

**Comment by ptkweller** [comment]
@rhyolight no our backlog isn't currently public but maybe for the client SDK we could change this.
I will have to discuss this with the team.
However, when we have looked at this request, we will add a comment to this issue.

**Comment by rhyolight** [comment]
Thanks!

**Comment by DarkmatterVale** [comment]
Thank you. That would be very appreciated if you would make it public.
